kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-storage-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1000Gi
  storageClassName: faang-nfs-sc