kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: validation-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: faang-nfs-sc